from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path
from typing import Sequence


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    existing = load_existing_examples(args.examples)
    rows = list(read_example_rows(args.examples))
    wanted = load_wanted_terms(args.ecdict, args.ecdict_tag)

    added = 0
    for key, term, translation in wanted:
        if key in existing:
            continue
        rows.append(
            {
                "term": term,
                "example": fallback_example(term, translation),
                "sentence_id": "",
                "author": "DanCLI",
                "source_name": "DanCLI fallback",
                "license": "Generated by DanCLI project",
            }
        )
        added += 1

    write_rows(args.out, rows)
    print(f"Wrote {len(rows)} examples to {args.out}")
    print(f"Added {added} fallback examples.")
    return 0


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fill missing example rows with clearly marked fallback examples.")
    parser.add_argument("--ecdict", type=Path, required=True, help="ECDICT CSV.")
    parser.add_argument("--ecdict-tag", action="append", required=True, help="Tag to include; repeatable.")
    parser.add_argument("--examples", type=Path, required=True, help="Existing examples CSV.")
    parser.add_argument("--out", type=Path, required=True, help="Output complete examples CSV.")
    return parser.parse_args(argv)


def load_existing_examples(path: Path) -> set[str]:
    result: set[str] = set()
    for row in read_example_rows(path):
        term = str(row.get("term", "")).strip()
        example = str(row.get("example", "")).strip()
        if term and example:
            result.add(term.casefold())
    return result


def read_example_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        return [{key: "" if value is None else value for key, value in row.items()} for row in reader]


def load_wanted_terms(path: Path, tags: Sequence[str]) -> list[tuple[str, str, str]]:
    wanted_tags = {tag.casefold() for tag in tags}
    rows: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    with path.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            term = first_value(row, "word", "term", "headword")
            if not term:
                continue
            row_tags = {tag.casefold() for tag in split_tags(row.get("tag", ""))}
            if not wanted_tags.intersection(row_tags):
                continue
            key = term.casefold()
            if key in seen:
                continue
            seen.add(key)
            rows.append((key, term, first_value(row, "translation", "definition", "meaning")))
    return rows


def fallback_example(term: str, translation: str) -> str:
    clean = normalize_term(term)
    lower = clean.lower()
    pos = detect_pos(translation)
    if " " in clean:
        return f"The phrase \"{clean}\" appears in this reading passage."
    if pos == "verb":
        return f"They tried to {lower} the situation carefully."
    if pos == "adjective":
        article = "an" if lower[:1] in {"a", "e", "i", "o", "u"} else "a"
        return f"The passage describes {article} {lower} change in the situation."
    if pos == "adverb":
        return f"She answered {lower} during the discussion."
    return f"The article uses \"{clean}\" in a clear context."


def normalize_term(term: str) -> str:
    return re.sub(r"\s+", " ", str(term).strip())


def detect_pos(translation: str) -> str:
    text = str(translation).lower()
    if re.search(r"(^|[;\n ])(vt|vi|v)\.", text):
        return "verb"
    if re.search(r"(^|[;\n ])(a|adj)\.", text):
        return "adjective"
    if re.search(r"(^|[;\n ])(ad|adv)\.", text):
        return "adverb"
    return "noun"


def write_rows(path: Path, rows: Sequence[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["term", "example", "sentence_id", "author", "source_name", "license"]
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in sorted(rows, key=lambda item: str(item.get("term", "")).casefold()):
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def first_value(mapping: dict[str, str], *keys: str) -> str:
    for key in keys:
        value = mapping.get(key)
        if value is not None and str(value).strip():
            return str(value).strip()
    return ""


def split_tags(value: str) -> list[str]:
    return [part.strip() for part in re.split(r"[,;|/\s]+", str(value or "")) if part.strip()]


if __name__ == "__main__":
    raise SystemExit(main())

